#!/usr/bin/env python3

import sys
import colorama
from src import lexer, parser, logging, generator

if __name__ == '__main__':
    colorama.init()

    lines = [line.replace('\n', ' ') for line in sys.stdin]

    tokens = lexer.tokenize(lines) 

    tree = parser.parse(tokens, lines)

    document = generator.generate(tree)

    print(document.content)
